import numpy as np
from Optimizer.FlowGen import *
from Optimizer.MapGen import *
from scipy.optimize import fsolve


def InitCoreComp(c):
    func = lambda x: x + x * np.log2(x) - c
    initial_guess = c / np.log2(c) if c > 1 else 1.0
    x_solution = fsolve(func, initial_guess)
    return x_solution[0]


def Initialize(Type:str, config:dict, MemorySize:int, BatchSize:int):
    """
    :input Type:
        The initialize type of the determined dataflow
        GridWorld —— the input data of the flow is generated by messages stored in
                     a 2d grid mesh
        MapWorld  —— the input data of the flow is generated by messages in a directed graph
        Others    —— the input data of the flow is generated by external input
    :input config:
        The details of the initialization process
    :input MemorySize:
        The size of the core memory ( # of packages, 32 bits per package )
    :input BatchSize:
        The size of one batch
    """
    if Type == "GridWorld":
        # 4bytes per package
        FullScaleX, FullScaleY = config["Scale"]
        TotalAgents = FullScaleX * FullScaleY * config["Density"] / 4
        MemoryReq = config["AgentBytes"] * BatchSize
        MinReqCores = min(np.ceil(MemoryReq / MemorySize),
                          np.ceil(config["AgentBytes"] * TotalAgents / MemorySize))
        PresentScale = np.ceil(np.sqrt(FullScaleY * FullScaleX / MinReqCores))
        Proc, Comm, Message, AgentNum = GridWorld(Scale=(PresentScale, PresentScale),
                                                Density=config["Density"],
                                                View=config["View"],
                                                ViewType=config["ViewType"],
                                                RBFactor=config["RBFactor"],
                                                CommEN=config["CommEN"],
                                                RandTimes=config["RandTimes"])
    elif Type == "MapWorld":
        # 4bytes per package
        MemoryReq = config["NodeBytes"] * config["NodeNum"] / 4
        ConnDegrees = np.random.randint(config["ConnDegree"][0], config["ConnDegree"][1],
                                        size=config["NodeNum"])
        MemoryReq += config["EdgeBytes"] * sum(ConnDegrees) / 2 / 4
        MinReqCores = np.ceil(MemoryReq / MemorySize)
        MinReqCores = min(MinReqCores, np.ceil(config['NodeNum'] / BatchSize * MinReqCores))
        PresentNodes = config["NodeNum"] / MinReqCores
        Proc, Comm, Message, AgentNum = MapWorld(NodeNum=PresentNodes,
                                                ConnDegree=config["ConnDegree"],
                                                TransDirectNum=config["TransDirect"],
                                                SearchFactor=config["SearchFactor"],
                                                CommEN=config["CommEN"],
                                                RandTimes=config["RandTimes"])
    else: # External Input
        Proc = config["Proc"]
        Comm = config["Commm"]
        Message = config["Message"]
        AgentNum = config["AgentNum"]
        MinReqCores = 0
    return Proc, Comm, Message, AgentNum, MinReqCores


def HardwareAdapt(CoreRatio:np.ndarray, ChipScale:tuple, BlockScale:tuple, CoreNum:int,
                  MemorySize:int, TimeCost:list, BatchSize:int, DRAMBandWidth:float, MinMemReq:int,
                  AgentNum:int, ClockCycle:int, IntBandWidth:float, StoMessage:list, Sparsity=1):
    """
    :input CoreRatio:
        Ideal non-stop dataflow ratio of different functions, layer 0 corresponding to the long-existing
        data of the algorithm
    :input ChipScale:
        Number of the chips (ChipX, ChipY)
    :input BlockScale:
        Number of the blocks in one chip (BlockX, BlockY)
    :input CoreNum:
        Number of the cores in one core
    :input BatchSize:
        The size of the batch
    :input AgentNum:
        The number of inference times
    :input TimeCost:
        The time cost for each level of the flow
    :input SendMessage:
        The number of messages send by each level of the flow
    :input MemorySize:
        The size of the memory in one core
    :input TimeCost:
        The time cost for each core to generate the output messages
    :input ExtBandWidth:
        The band width between chips
    """
    ChipX, ChipY = ChipScale
    BlockX, BlockY = BlockScale
    ChipCores = CoreNum * BlockX * BlockY
    TotalCores = ChipCores * ChipX * ChipY
    MaxCore = np.ones(CoreRatio.shape) * TotalCores
    MaxCore[1:] -= CoreRatio[:-1]
    IdealCoreRatio = np.zeros(len(CoreRatio))
    IdealPara = 0
    Repeat = 1
    InitPerBatch = max(np.floor(BatchSize / AgentNum), 1)
    DRAMReloadTime = (MemorySize * InitPerBatch) / (DRAMBandWidth * ClockCycle * 1e-3) * 32
    DRAMReloadTime = max(DRAMReloadTime,
                        (MemorySize * InitPerBatch) / (IntBandWidth * CoreRatio[0] * ClockCycle * 1e-3) * 32)
    DRAMReloadTime = np.ceil(DRAMReloadTime)
    if len(np.where(MaxCore < 0)[0]) == 0:
        # Parallel Batch Computation
        PolicyTime = sum([TimeCost[i] / CoreRatio[i] for i in range(1, len(CoreRatio))])
        MinBatchPreTime = DRAMReloadTime + TimeCost[0] / CoreRatio[0]
        Repeat = np.floor(CoreRatio[0] * AgentNum / BatchSize)
        if PolicyTime > MinBatchPreTime + DRAMReloadTime:
            MinPara = np.floor(((PolicyTime - DRAMReloadTime) / MinBatchPreTime + 1)).astype(int)
            MinPara = min(MinPara, len(CoreRatio) - 1)
            Gap = np.floor(len(CoreRatio) / MinPara).astype(int)
        else:
            MinPara = 1
            Gap = 1
        # Ping-pong kind mapping necessary core number
        EssCoresA = 0
        for i in range(1, max(len(CoreRatio) - Gap, 2)):
            TempCores = sum(CoreRatio[i:len(CoreRatio):MinPara])
            TempCores += sum(CoreRatio[i + 1:len(CoreRatio):MinPara])
            EssCoresA = max(TempCores, EssCoresA)
        EssCoresA *= 2
        # Thoughout kind mapping necessary core number
        EssCoresB = 0
        for i in range(1, max(int(len(CoreRatio) - 2 * MinPara), 2)):
            TempCores = sum(CoreRatio[i:int(i + 2 * MinPara + 1)])
            EssCoresB = max(TempCores, EssCoresB)
        EssCores = min(EssCoresA, EssCoresB) + CoreRatio[0]
        # Resource Adapt: Fold Judge
        SpatialPara = 0
        IdealPara = MinPara
        while EssCores <= TotalCores:
            # Idealest Case, directly deploy
            SpatialPara = np.floor(TotalCores / EssCores)
            IdealCoreRatio = CoreRatio * SpatialPara
            TotalCores -= EssCores * SpatialPara
        if TotalCores == 0:
            return np.zeros(IdealCoreRatio.shape), 0, IdealCoreRatio, IdealPara, Repeat, DRAMReloadTime
    else:
        EssCores = 0
        for i in range(len(CoreRatio) - 1):
            TempCores = sum(CoreRatio[i:i + 2])
            EssCores = max(TempCores, EssCores)
        EssCores = max(CoreRatio[0] + CoreRatio[-1], EssCores)
    # no ping-pong, deploy layer by layer
    ShrinkFactor = TotalCores / EssCores
    MinCore = np.ceil(np.array(StoMessage[:-1]) / MemorySize * Sparsity)
    MinCore = np.insert(MinCore, 0, MinMemReq).astype(int)
    EssCores = 0
    for i in range(len(MinCore) - 1):
        TempCores = sum(MinCore[i:i + 2])
        EssCores = max(EssCores, TempCores)
    if EssCores > TotalCores and len(np.where(MaxCore < 0)[0]) == 0:
        return np.zeros(IdealCoreRatio.shape), 0, IdealCoreRatio, IdealPara, Repeat, DRAMReloadTime
    elif EssCores > TotalCores:
        raise Exception("The hardware scale is too small or the batch size is too large.")
    NewCoreRatio = np.clip(np.floor(ShrinkFactor * CoreRatio), a_min=MinCore, a_max=None)
    NewCoreRatio[0] = min(NewCoreRatio[0], TotalCores - MinCore[1])
    NewRatioBatch = np.floor(NewCoreRatio[0] * AgentNum / BatchSize)
    StorageLim = min([np.floor(NewCoreRatio[i + 1] * MemorySize / StoMessage[i] / BatchSize)
                      for i in range(len(NewCoreRatio) - 1)])
    MinPara = min(NewRatioBatch, StorageLim)
    StartPoint = 0
    RestCores = TotalCores
    for Counter in range(len(NewCoreRatio)):
        RestCores -= NewCoreRatio[Counter]
        if Counter == len(NewCoreRatio) - 1 or RestCores < NewCoreRatio[Counter + 1]:
            IdealDist = CoreRatio[StartPoint:Counter + 1] - NewCoreRatio[StartPoint:Counter + 1]
            while RestCores > 0:
                Target = np.argsort(IdealDist)
                Index = StartPoint + Target[-1]
                if Index == len(NewCoreRatio) - 1 and NewCoreRatio[Index] + NewCoreRatio[0] == TotalCores:
                    NewCoreRatio[StartPoint + Target[-2]] += 1
                    IdealDist[Target[-2]] -= 1
                else:
                    NewCoreRatio[Index] += 1
                    IdealDist[Target[-1]] -= 1
                RestCores -= 1
            if StartPoint == 0:
                RestCores += sum(NewCoreRatio[StartPoint:Counter])
            else:
                RestCores += sum(NewCoreRatio[StartPoint - 1:Counter])
            StartPoint = Counter + 1
    return NewCoreRatio, MinPara, IdealCoreRatio, IdealPara, Repeat, DRAMReloadTime


def Genetic(ChipScale:tuple, BlockScale:tuple, CoreNum:int, DRAMBandWidth:float, Type:str,
            config:dict, IntBandWidth:float, BatchSize:int, InputFeature:tuple, DRAMLatency:int,
            Model:nn.Module, MemorySize:int, ClockCycle:int, NNSparsity:float=1):
    """
    :input ChipScale:
        Number of the chips (ChipX, ChipY)
    :input BlockScale:
        Number of the blocks in one chip (BlockX, BlockY)
    :input CoreNum:
        Number of the cores in one core
    :input ExtBandWidth:
        The bandwidth between different chips
    :input DRAMBandWidth:
        The bandwidth between chips and DRAM memory
    :input Type:
        The initialize type of the determined dataflow
        GridWorld —— the input data of the flow is generated by messages stored in
                     a 2d grid mesh
        MapWorld  —— the input data of the flow is generated by messages in a directed graph
        Others    —— the input data of the flow is generated by external input
    :input config:
        The details of the initialization process
    :input IntBandWidth:
        The bandwidth in one chip between different cores
    :input BatchSize:
        The size of the batch
    :input InputFeature:
        The shape of the input messages of the neural netowrk
    :input DRAMLatency:
        The latency of the DRAM data access
    :input Model:
        The neural network model for decision making
    :input MemorySize:
        The size of the core memory ( # of packages, 32 bits per package )
    :input ClockCycle:
        The digital clock period of the system (ns)
    """
    CoreRatio, TimeCost, SendMessage, StoMessage, Communication, NormRatio = NNPartition(
        IntBandWidth=IntBandWidth,
        BatchSize=BatchSize,
        InputFeature=InputFeature,
        DRAMLatency=DRAMLatency,
        Model=Model,
        MemorySize=MemorySize,
        ClockCycle=ClockCycle
    )
    # Analyse the long-existing data of the algorithm
    Proc, Comm, Message, AgentNum, MinReqCores = Initialize(
        Type=Type,
        config=config,
        MemorySize=MemorySize,
        BatchSize=BatchSize
    )
    # Idealest situation (no bandwidth bounding and infinite cores)
    if 'World' in Type:
        PreviousMessage = min(Message, Message / AgentNum * BatchSize)
        PreviousSendFlow = PreviousMessage / Proc / (StoMessage[0] * config['Density'])
        MaxBatchFlow = SendMessage[0] / TimeCost[0] / StoMessage[0]
        BatchCore = CoreRatio[0]
        InitCore = MinReqCores
        if PreviousMessage > MemorySize * BatchCore:
            Target = np.ceil(PreviousMessage / MemorySize)
            CoreRatio *= np.ceil(Target / BatchCore)
            BatchCore = Target
        if MaxBatchFlow * BatchCore  < PreviousSendFlow * InitCore * (1 + np.log2(InitCore)) * NormRatio:
            Target = np.ceil(PreviousSendFlow * InitCore * NormRatio / MaxBatchFlow)
            CoreRatio *= np.ceil(Target / BatchCore)
        elif MaxBatchFlow * BatchCore > PreviousSendFlow * InitCore * (1 + np.log2(InitCore)) * NormRatio:
            Target = np.floor(MaxBatchFlow * BatchCore / (PreviousSendFlow * NormRatio))
            InitCore = np.ceil(InitCoreComp(Target))
        CoreRatio = np.insert(CoreRatio, 0, InitCore)
        TimeCost.insert(0, Proc)
        Communication.insert(0, Comm)
        SendMessage.insert(0, Message)
        StoMessage.insert(0, Message)
    else:
        pass
    # Consider Hardware limitation
    SmallCoreRatio, SmallTimePara, IdealCoreRatio, IdealTimePara, Repeat, DRAMReloadTime = HardwareAdapt(
        CoreRatio=CoreRatio,
        ChipScale=ChipScale,
        BlockScale=BlockScale,
        CoreNum=CoreNum,
        StoMessage=StoMessage,
        MemorySize=MemorySize,
        TimeCost=TimeCost,
        DRAMBandWidth=DRAMBandWidth,
        IntBandWidth=IntBandWidth,
        MinMemReq=MinReqCores,
        AgentNum=AgentNum,
        BatchSize=BatchSize,
        ClockCycle=ClockCycle,
        Sparsity=NNSparsity
    )
    return SmallCoreRatio, SmallTimePara, IdealCoreRatio, IdealTimePara, Repeat, DRAMReloadTime, StoMessage
    # MapTry()
    # MapVari()
    # Sort()


def main():
    return


if __name__ == "__main__":
    main()